b:
	g++ -std=c++14 catchApple.cpp ApiAccess.cpp Setting.cpp Title.cpp Body.cpp MyCursor.cpp AppleCursor.cpp json11/json11.cpp -Wall -g -fsanitize=undefined -D_GLIBCXX_DEBUG -lncurses -lcurl -fno-rtti -fno-exceptions -O
	./a.out
